variables:
  - colname: "prec"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: |
      Notiamo dal Rsq 0.26 e dal p-value basso che ha senso considerare la varibile delle precipitazioni come predittore della mortalità. 
      Dall'analisi dei residui risulta che questi sono distribuiti attorno allo zero senza formare pattern e dal qqplot che si 
      distribuiscono secondo una distribuzione normale. Inoltre la distanza di Cook evidenzia 3 outlier che hanno un influenza importante
      sul modello, ovvero le osservazioni 32, 37 e 49 del dataset.
  - colname: "jant"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "jult"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "ovr65"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "popn"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "educ"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "hous"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "dens"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "nonw"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "wwdrk"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "poor"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "hc"
    tgcol: "mort"
    run: ["doscatterplot","dorsq", "uselog"]
    desc: ""
  - colname: "nox"
    tgcol: "mort"
    run: ["doscatterplot","dorsq", "uselog"]
    desc: ""
  - colname: "so2"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
  - colname: "humid"
    tgcol: "mort"
    run: ["doscatterplot","dorsq"]
    desc: ""
